version: '3.8'

services:
  dashboard:
    build: .
    ports:
      - "8501:8501"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8501/_stcore/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    volumes:
      - .:/app

  # tasker:
  #   image: strm/tasker
  #   volumes:
  #     - "/var/run/docker.sock:/var/run/docker.sock"
  #   environment:
  #     configuration: |
  #       schedule:
  #         - cron: 0 17 15 * * * # every day at 00:05
  #           task: get_data
  #       tasks:
  #         docker:
  #           - name: get_data
  #             image: python:3.9-slim
  #             script:
  #               - pip3 install -r requirements.txt
  #               - python3 get_data_from_metabase.py
  #             volumes:
  #               - .:/app
                  